### ISSUE TITLE
[추가] 200 상태코드 시 reponse 반환하기

### ISSUE THREAD

**Issue by Hejow** [USW-Flag-Board/Backend#113]
프론트 쪽에서 정상적으로 API를 호출했을 때 reponse를 반환해달라고 요청했습니다!
같이 고민해보면 좋을 것 같습니다!!

**Comment by Hejow** [comment]
현직 분에게 조언을 받은 결과 200 외에도 다른 상태에도 응답을 내려주는게 좋다고 합니다!
`{
  "payload" : "데이터",
  "result": {
    "status": "상태",
    "message": "상태에 대한 메세지"
  }
}`
로 할까 하는데 어떻게 생각하시나요??
`

**Comment by K-Diger** [comment]
`{
  "data" : object,
  "success":  boolean,
   "status": { 
       "code" : status code,
       "message": status message
    }
}`

위는 제가 아는 방법인데 편하신거 고르시면 될거같아요 불필요한 요소가 있는지 고민하게 되네요

**Comment by Hejow** [comment]
성공에 대한 값까지는 안 보내도 될 것 같단? 생각이라서 위에걸로 한번 해볼게요! 필요하다면 수정하면 되니까

**Comment by Hejow** [comment]
`{
  "payload" : 데이터,
   "status": 상태 코드,
   "message": 응답 메세지
}`
이렇게 만들었고 추후에 변경이 필요하다면 수정하겠습니다!
