### ISSUE TITLE
[개선] Post가 List<Reply> 들고있게끔 하기

### ISSUE THREAD

**Issue by gmltmd23** [USW-Flag-Board/Backend#24]
CASCADE REMOVE 옵션 필요
그에 따른 DB대응도 필요할듯

**Comment by Hejow** [comment]
지금 ERD 수정해야할거에요!!
게시판 카테고리도 추가가 되어야하니 따로 빼서 관리해야할 것 같습니다!
적당히 수정하시고 변경 사항만 말씀해주세요!
