### ISSUE TITLE
[개선] Post에 있는 List<Reply>에서 null을 들고있는 경우

### ISSUE THREAD

**Issue by gmltmd23** [USW-Flag-Board/Backend#29]
orphanRemoval을 사용하여 엔티티 제거를 하기에
List<Reply>에 있는 요소들을 null로 처리합니다.

그러다보니 리스트에 null이 쌓이는 경우가 존재합니다.
orphanRemoval을 사용하지않고 cascade 제거방식으로 가든지
아니면 주기적으로 null인것들을 비워줄지 골라야 할듯함

**Comment by Hejow** [comment]
오우야 이거 올린거 지금 봤어요! 주기적으로 제거하는 것도 나쁘지 않을거 같아요! user 쪽에서도 주기적으로 정리하는게 있거든요!
