### ISSUE TITLE
[추가] Board 패키지 생성하여 게시판과 검색 구현하기

### ISSUE THREAD

**Issue by gmltmd23** [USW-Flag-Board/Backend#48]
Board 패키지를 생성할 예정입니다.
* 해당 패키지에는 BoardController, BoardService, Board(Entity)를 만들 예정입니다.
* 현재 연관관계가 Category - Post가 1 : N 관계인데, Board를 만들게 되면 Category - Board - Post로
   1:1:N 관계가 될 예정입니다.
* Board 패키지에서 Search 기능 또한 구현 될 예정입니다.

**Comment by gmltmd23** [comment]
Board의 엔티티는 필요없을수도 있기에
Board의 엔티티를 만들어서 진행하는 케이스,
Board의 엔티티를 만들지 않고 진행하는 케이스

두 가지중 효율적인것을 선택하여 구현할 예정

**Comment by K-Diger** [comment]
Board가 어떤 책임을 가지고 있는건가요?

지금 만들어진 카테고리가 그 책임을 대체하는 것 처럼 보이기도 해서요

**Comment by gmltmd23** [comment]
@K-Diger 
Category와 동일한 책임을 가지고 있는것이 맞습니다.
근데 해당 Issue를 작성할 당시 컨셉이 명확히 정해지지않아 일단 Issue를 깃허브에 업로드만 해놓은것이라서요,
Category만 쓰든지, Board를 쓰든지 확실히 정해서 개발 진행 예정입니다.

**Comment by K-Diger** [comment]
아하.. 기획적인 문제였군요 전체 회의때 이야기 해보면 좋을것같네요!

**Comment by gmltmd23** [comment]
Search 패키지를 별도로 만들어 진행하는것으로 기획방향 잡혀 구현 시작합니다.
