### ISSUE TITLE
[추가] 유저 검색 구현 

### ISSUE THREAD

**Issue by sdoaolo** [USW-Flag-Board/Backend#73]
#### 담당자 : @sdoaolo 

- UserSearchController
- UserSearchService

<br>

- 유저 검색시 이름만으로 검색이 들어가야하므로  요청메세지는 다음과 같습니다.
     GET  http://localhost:8080/api/user?name=강지은 

<br>

- Response는 List<>로 넘겨줄 예정입니다 😃

**Comment by Hejow** [comment]
혹시 이 컨트롤러가 필요한 이유가 있을까요?

**Comment by sdoaolo** [comment]
### ✅ ( #75 Search 패키지 제거 ) 에 의해  해당 이슈 close
유저 검색 기능은 Member에게 위임 됨
